name: Publish to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Extract version from tag
        id: get_version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$TAG_VERSION" >> $GITHUB_ENV
          echo "📦 Publishing version: $TAG_VERSION"

      - name: Install dependencies
        run: |
          # Update pip
          python -m pip install --upgrade pip
          # Install only the dependencies required for building, not the full project dependencies
          pip install build twine wheel

      - name: Update version in pyproject.toml
        run: |
          # Replace version in pyproject.toml with the tag version
          sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          echo "✅ Updated version in pyproject.toml to $VERSION"
          grep "version =" pyproject.toml

      - name: Build package
        run: |
          python -m build
          echo "✅ Package built successfully"
          ls -la dist/

      - name: Check package
        run: |
          twine check dist/*
          echo "✅ Package verification passed"

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
